                indexname                 |                                                          indexdef                                                           
------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------
 idx_bank_import_sessions_account         | CREATE INDEX idx_bank_import_sessions_account ON public.bank_import_sessions USING btree (bank_account_id)
 idx_bank_import_sessions_filename        | CREATE INDEX idx_bank_import_sessions_filename ON public.bank_import_sessions USING btree (import_filename)
 idx_bank_import_sessions_date            | CREATE INDEX idx_bank_import_sessions_date ON public.bank_import_sessions USING btree (imported_at)
 idx_audit_log_timestamp                  | CREATE INDEX idx_audit_log_timestamp ON public.audit_log USING btree ("timestamp")
 idx_audit_log_table_record               | CREATE INDEX idx_audit_log_table_record ON public.audit_log USING btree (table_name, record_id)
 idx_suppliers_normalized_name            | CREATE INDEX idx_suppliers_normalized_name ON public.suppliers USING btree (normalized_name)
 idx_suppliers_category                   | CREATE INDEX idx_suppliers_category ON public.suppliers USING btree (category)
 idx_suppliers_active                     | CREATE INDEX idx_suppliers_active ON public.suppliers USING btree (is_active)
 idx_suppliers_created_at                 | CREATE INDEX idx_suppliers_created_at ON public.suppliers USING btree (created_at)
 idx_suppliers_name_fts                   | CREATE INDEX idx_suppliers_name_fts ON public.suppliers USING gin (to_tsvector('german'::regconfig, (name)::text))
 idx_items_org_active                     | CREATE INDEX idx_items_org_active ON public.items USING btree (organization_id, active)
 idx_bank_accounts_user_active            | CREATE INDEX idx_bank_accounts_user_active ON public.bank_accounts USING btree (user_id, is_active)
 idx_bank_accounts_iban                   | CREATE INDEX idx_bank_accounts_iban ON public.bank_accounts USING btree (iban)
 idx_bank_accounts_org_active             | CREATE INDEX idx_bank_accounts_org_active ON public.bank_accounts USING btree (organization_id, is_active)
 idx_provider_reports_provider_status     | CREATE INDEX idx_provider_reports_provider_status ON public.provider_reports USING btree (provider, status)
 idx_provider_reports_transaction_date    | CREATE INDEX idx_provider_reports_transaction_date ON public.provider_reports USING btree (transaction_date)
 idx_provider_reports_sale_id             | CREATE INDEX idx_provider_reports_sale_id ON public.provider_reports USING btree (sale_id)
 idx_provider_reports_import_date         | CREATE INDEX idx_provider_reports_import_date ON public.provider_reports USING btree (import_date)
 idx_document_sequences_type              | CREATE INDEX idx_document_sequences_type ON public.document_sequences USING btree (type)
 business_settings_user_org_unique        | CREATE UNIQUE INDEX business_settings_user_org_unique ON public.business_settings USING btree (user_id, organization_id)
 unique_bank_reference_per_account        | CREATE UNIQUE INDEX unique_bank_reference_per_account ON public.bank_transactions USING btree (bank_account_id, reference)
 idx_bank_transactions_reference          | CREATE INDEX idx_bank_transactions_reference ON public.bank_transactions USING btree (reference)
 idx_bank_transactions_import_filename    | CREATE INDEX idx_bank_transactions_import_filename ON public.bank_transactions USING btree (import_filename)
 idx_bank_transactions_booking_date       | CREATE INDEX idx_bank_transactions_booking_date ON public.bank_transactions USING btree (booking_date)
 idx_bank_transactions_status_date        | CREATE INDEX idx_bank_transactions_status_date ON public.bank_transactions USING btree (status, transaction_date)
 idx_bank_transactions_number             | CREATE INDEX idx_bank_transactions_number ON public.bank_transactions USING btree (transaction_number)
 idx_bank_transactions_account_date       | CREATE INDEX idx_bank_transactions_account_date ON public.bank_transactions USING btree (bank_account_id, transaction_date)
 idx_bank_transactions_status             | CREATE INDEX idx_bank_transactions_status ON public.bank_transactions USING btree (status)
 idx_bank_transactions_amount             | CREATE INDEX idx_bank_transactions_amount ON public.bank_transactions USING btree (amount)
 idx_bank_transactions_import_batch       | CREATE INDEX idx_bank_transactions_import_batch ON public.bank_transactions USING btree (import_batch_id)
 idx_owner_transactions_type              | CREATE INDEX idx_owner_transactions_type ON public.owner_transactions USING btree (transaction_type)
 idx_owner_transactions_date              | CREATE INDEX idx_owner_transactions_date ON public.owner_transactions USING btree (transaction_date)
 idx_owner_transactions_user_id           | CREATE INDEX idx_owner_transactions_user_id ON public.owner_transactions USING btree (user_id)
 idx_owner_transactions_payment_method    | CREATE INDEX idx_owner_transactions_payment_method ON public.owner_transactions USING btree (payment_method)
 idx_owner_transactions_banking_status    | CREATE INDEX idx_owner_transactions_banking_status ON public.owner_transactions USING btree (banking_status)
 idx_owner_transactions_related_expense   | CREATE INDEX idx_owner_transactions_related_expense ON public.owner_transactions USING btree (related_expense_id)
 idx_transaction_matches_bank_transaction | CREATE INDEX idx_transaction_matches_bank_transaction ON public.transaction_matches USING btree (bank_transaction_id)
 idx_transaction_matches_matched_type_id  | CREATE INDEX idx_transaction_matches_matched_type_id ON public.transaction_matches USING btree (matched_type, matched_id)
 idx_transaction_matches_confidence       | CREATE INDEX idx_transaction_matches_confidence ON public.transaction_matches USING btree (match_confidence)
 idx_cash_movements_number                | CREATE INDEX idx_cash_movements_number ON public.cash_movements USING btree (movement_number)
 idx_cash_movements_created_at            | CREATE INDEX idx_cash_movements_created_at ON public.cash_movements USING btree (created_at)
 idx_cash_movements_user_id               | CREATE INDEX idx_cash_movements_user_id ON public.cash_movements USING btree (user_id)
 idx_cash_movements_bank_transaction      | CREATE INDEX idx_cash_movements_bank_transaction ON public.cash_movements USING btree (bank_transaction_id)
 idx_cash_movements_movement_type         | CREATE INDEX idx_cash_movements_movement_type ON public.cash_movements USING btree (movement_type)
 idx_cash_movements_org_date              | CREATE INDEX idx_cash_movements_org_date ON public.cash_movements USING btree (organization_id, created_at DESC)
 idx_documents_document_number            | CREATE INDEX idx_documents_document_number ON public.documents USING btree (document_number)
 idx_documents_type                       | CREATE INDEX idx_documents_type ON public.documents USING btree (type)
 idx_documents_document_date              | CREATE INDEX idx_documents_document_date ON public.documents USING btree (document_date)
 idx_documents_user_id                    | CREATE INDEX idx_documents_user_id ON public.documents USING btree (user_id)
 idx_documents_reference_type_id          | CREATE INDEX idx_documents_reference_type_id ON public.documents USING btree (reference_type, reference_id)
 idx_documents_type_date                  | CREATE INDEX idx_documents_type_date ON public.documents USING btree (type, document_date)
 idx_documents_user_type                  | CREATE INDEX idx_documents_user_type ON public.documents USING btree (user_id, type)
 idx_documents_org_type                   | CREATE INDEX idx_documents_org_type ON public.documents USING btree (organization_id, type)
 idx_expenses_receipt_number              | CREATE INDEX idx_expenses_receipt_number ON public.expenses USING btree (receipt_number)
 idx_expenses_supplier_id                 | CREATE INDEX idx_expenses_supplier_id ON public.expenses USING btree (supplier_id)
 idx_expenses_payment_date                | CREATE INDEX idx_expenses_payment_date ON public.expenses USING btree (payment_date)
 idx_expenses_category                    | CREATE INDEX idx_expenses_category ON public.expenses USING btree (category)
 idx_expenses_user_id                     | CREATE INDEX idx_expenses_user_id ON public.expenses USING btree (user_id)
 idx_expenses_bank_transaction            | CREATE INDEX idx_expenses_bank_transaction ON public.expenses USING btree (bank_transaction_id)
 idx_expenses_org_date                    | CREATE INDEX idx_expenses_org_date ON public.expenses USING btree (organization_id, payment_date DESC)
 idx_daily_summaries_report_date          | CREATE INDEX idx_daily_summaries_report_date ON public.daily_summaries USING btree (report_date)
 idx_daily_summaries_created_by           | CREATE INDEX idx_daily_summaries_created_by ON public.daily_summaries USING btree (created_by)
 idx_monthly_summaries_year_month         | CREATE INDEX idx_monthly_summaries_year_month ON public.monthly_summaries USING btree (year, month)
 idx_monthly_summaries_created_by         | CREATE INDEX idx_monthly_summaries_created_by ON public.monthly_summaries USING btree (created_by)
 idx_sales_receipt_number                 | CREATE INDEX idx_sales_receipt_number ON public.sales USING btree (receipt_number)
 idx_sales_created_at                     | CREATE INDEX idx_sales_created_at ON public.sales USING btree (created_at)
 idx_sales_payment_method                 | CREATE INDEX idx_sales_payment_method ON public.sales USING btree (payment_method)
 idx_sales_user_id                        | CREATE INDEX idx_sales_user_id ON public.sales USING btree (user_id)
 idx_sales_provider_report                | CREATE INDEX idx_sales_provider_report ON public.sales USING btree (provider_report_id)
 idx_sales_bank_transaction               | CREATE INDEX idx_sales_bank_transaction ON public.sales USING btree (bank_transaction_id)
 idx_sales_banking_status                 | CREATE INDEX idx_sales_banking_status ON public.sales USING btree (banking_status)
 idx_sales_org_created                    | CREATE INDEX idx_sales_org_created ON public.sales USING btree (organization_id, created_at DESC)
(72 rows)

