# Simplified Docker Compose for Coolify
# Deploy as separate services in Coolify for better management

version: '3.8'

services:
  # Main NextJS Application - Deploy this as primary app in Coolify
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=https://db.lia-hair.ch
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Supabase Stack - Deploy this as separate app in Coolify
  supabase:
    image: supabase/supabase:latest
    ports:
      - "8000:8000"  # API Gateway
      - "5432:5432"  # PostgreSQL (if needed for external tools)
    environment:
      # Database
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=supabase_admin
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=3600
      
      # Auth Configuration
      - SITE_URL=https://pos.lia-hair.ch
      - API_EXTERNAL_URL=https://db.lia-hair.ch
      - ADDITIONAL_REDIRECT_URLS=https://pos.lia-hair.ch/auth/callback
      - DISABLE_SIGNUP=true
      - ENABLE_EMAIL_CONFIRMATIONS=true
      - ENABLE_EMAIL_AUTOCONFIRM=false
      - ENABLE_ANONYMOUS_USERS=false
      
      # SMTP Configuration (optional)
      - SMTP_ADMIN_EMAIL=${SMTP_ADMIN_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SENDER_NAME="LIA Hair POS System"
      
      # Service Keys
      - ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # Database Schema
      - PGRST_DB_SCHEMAS=public,auth,storage
      
    volumes:
      - supabase_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/rest/v1/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  supabase_data:
    driver: local

networks:
  default:
    name: coolify