-- ============================================================================
-- PERFORMANCE INDEXES: Custom indexes for optimization  
-- ============================================================================
-- Note: Uses IF NOT EXISTS to avoid conflicts with table-level indexes

 CREATE INDEX IF NOT EXISTS idx_audit_log_table_record ON public.audit_log USING btree (table_name, record_id);
 CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON public.audit_log USING btree ("timestamp");
 CREATE INDEX IF NOT EXISTS idx_bank_accounts_iban ON public.bank_accounts USING btree (iban);
 CREATE INDEX IF NOT EXISTS idx_bank_accounts_org_active ON public.bank_accounts USING btree (organization_id, is_active);
 CREATE INDEX IF NOT EXISTS idx_bank_accounts_user_active ON public.bank_accounts USING btree (user_id, is_active);
 CREATE INDEX IF NOT EXISTS idx_bank_import_sessions_account ON public.bank_import_sessions USING btree (bank_account_id);
 CREATE INDEX IF NOT EXISTS idx_bank_import_sessions_date ON public.bank_import_sessions USING btree (imported_at);
 CREATE INDEX IF NOT EXISTS idx_bank_import_sessions_filename ON public.bank_import_sessions USING btree (import_filename);
 CREATE UNIQUE INDEX IF NOT EXISTS bank_transactions_transaction_number_key ON public.bank_transactions USING btree (transaction_number);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_account_date ON public.bank_transactions USING btree (bank_account_id, transaction_date);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_amount ON public.bank_transactions USING btree (amount);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_booking_date ON public.bank_transactions USING btree (booking_date);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_import_batch ON public.bank_transactions USING btree (import_batch_id);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_import_filename ON public.bank_transactions USING btree (import_filename);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_number ON public.bank_transactions USING btree (transaction_number);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_reference ON public.bank_transactions USING btree (reference);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_status ON public.bank_transactions USING btree (status);
 CREATE INDEX IF NOT EXISTS idx_bank_transactions_status_date ON public.bank_transactions USING btree (status, transaction_date);
 CREATE UNIQUE INDEX IF NOT EXISTS unique_bank_reference_per_account ON public.bank_transactions USING btree (bank_account_id, reference);
 CREATE UNIQUE INDEX IF NOT EXISTS business_settings_user_org_unique ON public.business_settings USING btree (user_id, organization_id);
 CREATE UNIQUE INDEX IF NOT EXISTS cash_movements_movement_number_key ON public.cash_movements USING btree (movement_number);
 CREATE INDEX IF NOT EXISTS idx_cash_movements_bank_transaction ON public.cash_movements USING btree (bank_transaction_id);
 CREATE INDEX IF NOT EXISTS idx_cash_movements_created_at ON public.cash_movements USING btree (created_at);
 CREATE INDEX IF NOT EXISTS idx_cash_movements_movement_type ON public.cash_movements USING btree (movement_type);
 CREATE INDEX IF NOT EXISTS idx_cash_movements_number ON public.cash_movements USING btree (movement_number);
 CREATE INDEX IF NOT EXISTS idx_cash_movements_org_date ON public.cash_movements USING btree (organization_id, created_at DESC);
 CREATE INDEX IF NOT EXISTS idx_cash_movements_user_id ON public.cash_movements USING btree (user_id);
 CREATE UNIQUE INDEX IF NOT EXISTS daily_summaries_report_date_key ON public.daily_summaries USING btree (report_date);
 CREATE INDEX IF NOT EXISTS idx_daily_summaries_created_by ON public.daily_summaries USING btree (created_by);
 CREATE INDEX IF NOT EXISTS idx_daily_summaries_report_date ON public.daily_summaries USING btree (report_date);
 CREATE INDEX IF NOT EXISTS idx_document_sequences_type ON public.document_sequences USING btree (type);
 CREATE UNIQUE INDEX IF NOT EXISTS documents_document_number_key ON public.documents USING btree (document_number);
 CREATE INDEX IF NOT EXISTS idx_documents_document_date ON public.documents USING btree (document_date);
 CREATE INDEX IF NOT EXISTS idx_documents_document_number ON public.documents USING btree (document_number);
 CREATE INDEX IF NOT EXISTS idx_documents_org_type ON public.documents USING btree (organization_id, type);
 CREATE INDEX IF NOT EXISTS idx_documents_reference_type_id ON public.documents USING btree (reference_type, reference_id);
 CREATE INDEX IF NOT EXISTS idx_documents_type ON public.documents USING btree (type);
 CREATE INDEX IF NOT EXISTS idx_documents_type_date ON public.documents USING btree (type, document_date);
 CREATE INDEX IF NOT EXISTS idx_documents_user_id ON public.documents USING btree (user_id);
 CREATE INDEX IF NOT EXISTS idx_documents_user_type ON public.documents USING btree (user_id, type);
 CREATE UNIQUE INDEX IF NOT EXISTS expenses_receipt_number_key ON public.expenses USING btree (receipt_number);
 CREATE INDEX IF NOT EXISTS idx_expenses_bank_transaction ON public.expenses USING btree (bank_transaction_id);
 CREATE INDEX IF NOT EXISTS idx_expenses_category ON public.expenses USING btree (category);
 CREATE INDEX IF NOT EXISTS idx_expenses_org_date ON public.expenses USING btree (organization_id, payment_date DESC);
 CREATE INDEX IF NOT EXISTS idx_expenses_payment_date ON public.expenses USING btree (payment_date);
 CREATE INDEX IF NOT EXISTS idx_expenses_receipt_number ON public.expenses USING btree (receipt_number);
 CREATE INDEX IF NOT EXISTS idx_expenses_supplier_id ON public.expenses USING btree (supplier_id);
 CREATE INDEX IF NOT EXISTS idx_expenses_user_id ON public.expenses USING btree (user_id);
 CREATE INDEX IF NOT EXISTS idx_items_org_active ON public.items USING btree (organization_id, active);
 CREATE INDEX IF NOT EXISTS idx_monthly_summaries_created_by ON public.monthly_summaries USING btree (created_by);
 CREATE INDEX IF NOT EXISTS idx_monthly_summaries_year_month ON public.monthly_summaries USING btree (year, month);
 CREATE UNIQUE INDEX IF NOT EXISTS monthly_summaries_year_month_key ON public.monthly_summaries USING btree (year, month);
 CREATE UNIQUE INDEX IF NOT EXISTS organization_users_organization_id_user_id_key ON public.organization_users USING btree (organization_id, user_id);
 CREATE UNIQUE INDEX IF NOT EXISTS organizations_slug_key ON public.organizations USING btree (slug);
 CREATE INDEX IF NOT EXISTS idx_owner_transactions_banking_status ON public.owner_transactions USING btree (banking_status);
 CREATE INDEX IF NOT EXISTS idx_owner_transactions_date ON public.owner_transactions USING btree (transaction_date);
 CREATE INDEX IF NOT EXISTS idx_owner_transactions_payment_method ON public.owner_transactions USING btree (payment_method);
 CREATE INDEX IF NOT EXISTS idx_owner_transactions_related_expense ON public.owner_transactions USING btree (related_expense_id);
 CREATE INDEX IF NOT EXISTS idx_owner_transactions_type ON public.owner_transactions USING btree (transaction_type);
 CREATE INDEX IF NOT EXISTS idx_owner_transactions_user_id ON public.owner_transactions USING btree (user_id);
 CREATE INDEX IF NOT EXISTS idx_provider_reports_import_date ON public.provider_reports USING btree (import_date);
 CREATE INDEX IF NOT EXISTS idx_provider_reports_provider_status ON public.provider_reports USING btree (provider, status);
 CREATE INDEX IF NOT EXISTS idx_provider_reports_sale_id ON public.provider_reports USING btree (sale_id);
 CREATE INDEX IF NOT EXISTS idx_provider_reports_transaction_date ON public.provider_reports USING btree (transaction_date);
 CREATE INDEX IF NOT EXISTS idx_sales_bank_transaction ON public.sales USING btree (bank_transaction_id);
 CREATE INDEX IF NOT EXISTS idx_sales_banking_status ON public.sales USING btree (banking_status);
 CREATE INDEX IF NOT EXISTS idx_sales_created_at ON public.sales USING btree (created_at);
 CREATE INDEX IF NOT EXISTS idx_sales_org_created ON public.sales USING btree (organization_id, created_at DESC);
 CREATE INDEX IF NOT EXISTS idx_sales_payment_method ON public.sales USING btree (payment_method);
 CREATE INDEX IF NOT EXISTS idx_sales_provider_report ON public.sales USING btree (provider_report_id);
 CREATE INDEX IF NOT EXISTS idx_sales_receipt_number ON public.sales USING btree (receipt_number);
 CREATE INDEX IF NOT EXISTS idx_sales_user_id ON public.sales USING btree (user_id);
 CREATE UNIQUE INDEX IF NOT EXISTS sales_receipt_number_key ON public.sales USING btree (receipt_number);
 CREATE INDEX IF NOT EXISTS idx_suppliers_active ON public.suppliers USING btree (is_active);
 CREATE INDEX IF NOT EXISTS idx_suppliers_category ON public.suppliers USING btree (category);
 CREATE INDEX IF NOT EXISTS idx_suppliers_created_at ON public.suppliers USING btree (created_at);
 CREATE INDEX IF NOT EXISTS idx_suppliers_name_fts ON public.suppliers USING gin (to_tsvector('german'::regconfig, (name)::text));
 CREATE INDEX IF NOT EXISTS idx_suppliers_normalized_name ON public.suppliers USING btree (normalized_name);
 CREATE UNIQUE INDEX IF NOT EXISTS suppliers_normalized_name_key ON public.suppliers USING btree (normalized_name);
 CREATE INDEX IF NOT EXISTS idx_transaction_matches_bank_transaction ON public.transaction_matches USING btree (bank_transaction_id);
 CREATE INDEX IF NOT EXISTS idx_transaction_matches_confidence ON public.transaction_matches USING btree (match_confidence);
 CREATE INDEX IF NOT EXISTS idx_transaction_matches_matched_type_id ON public.transaction_matches USING btree (matched_type, matched_id);
 CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON public.users USING btree (email);
 CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON public.users USING btree (username);

